export const DB = process.env.DB || 'dev'
export const PORT = process.env.PORT || '3000'
export const SECRET = process.env.SECRET || 'devsecret'
export const PRIVATEKEY = process.env.PRIVATEKEY || ''
export const CERTIFICATE = process.env.CERTIFICATE || ''
